kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: per-cluster
spec:
  repo: https://github.com/manno/fleet-experiments
  branch: main
  paths:
    - chart-per-cluster
  targets:
    - clusterSelector: {}
