kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: cert-manager

spec:
  repo: https://github.com/manno/fleet-experiments
  branch: cert-manager
  paths:
  - cert-manager

  targets:
  - clusterSelector:
      matchExpressions:
      - key: provider.cattle.io
        operator: NotIn
        values:
        - harvester
