kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: experiment
spec:
  repo: https://github.com/manno/fleet-experiments
  branch: main
  paths:
    - dependson/root
  targets:
    - clusterSelector: {}
