apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: testsecrets.test.example.org
spec:
  conversion:
    strategy: None
  group: test.example.org
  names:
    kind: TestSecret
    listKind: TestSecretList
    plural: testsecrets
    shortNames:
    - qsec
    - qsecs
    singular: testsecret
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              copies:
                description: A list of namespaced names where to copy generated secrets
                items:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                type: array
              request:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              secretLabels:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              secretAnnotations:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              secretName:
                description: The name of the generated secret
                minLength: 1
                type: string
              type:
                description: 'What kind of secret to generate: password, certificate,
                  ssh, rsa, basic-auth'
                minLength: 1
                type: string
            required:
            - secretName
            - type
            type: object
          status:
            properties:
              generated:
                type: boolean
              lastReconcile:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
