apiVersion: batch/v1
kind: Job
metadata:
  name: job-with-ttlsecondsafterfinished
spec:
  ttlSecondsAfterFinished: 5
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: sleep-ignore
          command:
            - sleep
            - "10"
          image: rancher/mirrored-library-busybox:1.34.1
          imagePullPolicy: IfNotPresent
