apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: default.test.fleet.rancher.io
    http:
      paths:
      - backend:
          service:
            name: health
            port:
              number: 9000
        path: /health
        pathType: ImplementationSpecific
