apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleeper
  labels:
    fleet: testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleeper
  template:
    metadata:
      labels:
        app: sleeper
    spec:
      containers:
        - name: sleep
          command:
            - sleep
            - 7d
          image: "rancher/mirrored-library-busybox:1.34.1"
          imagePullPolicy: IfNotPresent
