---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: processes.day3.cloud
spec:
  conversion:
    strategy: None
  group: day3.cloud
  names:
    kind: Process
    listKind: ProcessList
    singular: process
    plural: processes
    shortNames:
    - proc
  preserveUnknownFields: false
  scope: Namespaced
  versions:
    - name: v1alpha1
      storage: false
      served: false
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
    - name: v1alpha2
      storage: false
      served: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
    - name: v1beta1
      storage: true
      served: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
