apiVersion: v1
kind: ConfigMap
metadata:
  name: install-config
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-3"
    "helm.sh/resource-policy": keep
data:
  TZ: {{ .Values.timezone | quote }}
  test: install test
